### Get work list
GET http://localhost:8080/work/list HTTP/1.1
Content-Type: application/json

### Create work
POST http://localhost:8080/work/create HTTP/1.1
Content-Type: application/json

{
  "workName": "Test work"
}

### Update work
POST http://localhost:8080/work/update HTTP/1.1
Content-Type: application/json

{
  "id": 4,
  "workName": "Test work updated"
}

### Delete work
POST http://localhost:8080/work/delete/4 HTTP/1.1
Content-Type: application/json