server:
  port: 8080
  servlet:
    session:
      timeout: 6000m
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timenest?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    mapUnderscoreToCamelCase: true